name: Test robusta with pytest

on: [push]

jobs:
    run_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Create k8s Kind Cluster
          uses: helm/kind-action@v1.2.0
        - name: Install Robusta
          run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            cd src/
            poetry config virtualenvs.create false
            poetry install --extras "all"
        - name: Test Robusta
          env:
            PYTEST_SLACK_TOKEN: ${{ secrets.PYTEST_SLACK_TOKEN }}
            PYTEST_IN_CLUSTER_SLACK_TOKEN: ${{ secrets.PYTEST_IN_CLUSTER_SLACK_TOKEN }}
          run: |
            source $HOME/.poetry/env
            cd src/
            pytest .. -s
