name: Test Skaffold Caching

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Test'
        required: false

env:
  PROJECT_ID: ${{ secrets.GKE_PROD_PROJECT }}

jobs:
  setup-build-publish-deploy:
    name: Build images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_PROD_SA_KEY }}
        project_id: ${{ secrets.GKE_PROD_PROJECT }}
        export_default_credentials: true

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - run: |-
        gcloud config get-value project

    - run: |-
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod a+x skaffold

    - name: Update package version
      run: |
        sed -i 's/0.0.0/${{env.RELEASE_VER}}/g' src/robusta/_version.py src/pyproject.toml

    - name: list files
      run: "ls ~/.skaffold/"

    # see https://github.com/GoogleContainerTools/skaffold/issues/4842
    - name: Cache skaffold image builds & config
      uses: actions/cache@v2
      with:
        path: ~/.skaffold/
        key: fixed-${{ github.sha }}
        restore-keys: |
          fixed-${{ github.sha }}
          fixed-

    - name: list files2
      run: "ls ~/.skaffold/"

    - name: Build with skaffold
      run: ./skaffold build --file-output=container-ids.json

    - name: list files3
      run: "ls ~/.skaffold/"
